# This is a basic workflow to help you get started with Actions

name: Bump version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    # prevent infinite loop since this action may commit and change these 2 files
    paths-ignore:
    - './react-context/package.json'
    - './react-context/CHANGELOG.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BUMP_VERSION_TOKEN }}
      - name: Bump version and push tag
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.BUMP_VERSION_TOKEN }}
          git-message: 'chore(release): {version}'
          preset: 'angular'
          tag-prefix: ''
          output-file: 'false'
          version-file: './react-context/package.json'
